# Generated by Django 4.1.2 on 2022-10-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_alter_customer_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="profile_pic",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
